// <auto-generated />
using System;
using AnalysisTagger.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnalysisTagger.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424201439_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("AnalysisTagger.Domain.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("DefaultLagTime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DefaultLeadTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubCategories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TagTemplateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagTemplateId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.DrawingAnnotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EventTagId")
                        .HasColumnType("TEXT");

                    b.Property<long>("FrameTimecode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerializedDrawingData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventTagId");

                    b.ToTable("DrawingAnnotations");
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.EventTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EventTags");
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomAttributes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShirtNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.PlaylistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("TagId");

                    b.ToTable("PlaylistEntries");
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Competition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sport")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaggingMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.TagTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sport")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("TagTemplates");
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShieldImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("EventTagPlayers", b =>
                {
                    b.Property<Guid>("EventTagId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaggedPlayersId")
                        .HasColumnType("TEXT");

                    b.HasKey("EventTagId", "TaggedPlayersId");

                    b.HasIndex("TaggedPlayersId");

                    b.ToTable("EventTagPlayers");
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.Category", b =>
                {
                    b.HasOne("AnalysisTagger.Domain.Models.TagTemplate", null)
                        .WithMany("Categories")
                        .HasForeignKey("TagTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.DrawingAnnotation", b =>
                {
                    b.HasOne("AnalysisTagger.Domain.Models.EventTag", null)
                        .WithMany("Drawings")
                        .HasForeignKey("EventTagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.EventTag", b =>
                {
                    b.HasOne("AnalysisTagger.Domain.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnalysisTagger.Domain.Models.Project", null)
                        .WithMany("Events")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("AnalysisTagger.Domain.ValueObjects.VideoSegment", "Segment", b1 =>
                        {
                            b1.Property<Guid>("EventTagId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("End")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SegmentEndTicks");

                            b1.Property<long>("Start")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SegmentStartTicks");

                            b1.HasKey("EventTagId");

                            b1.ToTable("EventTags");

                            b1.WithOwner()
                                .HasForeignKey("EventTagId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Segment")
                        .IsRequired();
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.Player", b =>
                {
                    b.HasOne("AnalysisTagger.Domain.Models.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.Playlist", b =>
                {
                    b.HasOne("AnalysisTagger.Domain.Models.Project", null)
                        .WithMany("Playlists")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.PlaylistEntry", b =>
                {
                    b.HasOne("AnalysisTagger.Domain.Models.Playlist", null)
                        .WithMany("Entries")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AnalysisTagger.Domain.Models.EventTag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AnalysisTagger.Domain.ValueObjects.VideoSegment", "SegmentOverride", b1 =>
                        {
                            b1.Property<Guid>("PlaylistEntryId")
                                .HasColumnType("TEXT");

                            b1.Property<long>("End")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SegmentOverrideEndTicks");

                            b1.Property<long>("Start")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SegmentOverrideStartTicks");

                            b1.HasKey("PlaylistEntryId");

                            b1.ToTable("PlaylistEntries");

                            b1.WithOwner()
                                .HasForeignKey("PlaylistEntryId");
                        });

                    b.Navigation("SegmentOverride");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.Project", b =>
                {
                    b.HasOne("AnalysisTagger.Domain.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnalysisTagger.Domain.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.TagTemplate", b =>
                {
                    b.HasOne("AnalysisTagger.Domain.Models.Project", null)
                        .WithOne("Template")
                        .HasForeignKey("AnalysisTagger.Domain.Models.TagTemplate", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EventTagPlayers", b =>
                {
                    b.HasOne("AnalysisTagger.Domain.Models.EventTag", null)
                        .WithMany()
                        .HasForeignKey("EventTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnalysisTagger.Domain.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("TaggedPlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.EventTag", b =>
                {
                    b.Navigation("Drawings");
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.Playlist", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.Project", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Playlists");

                    b.Navigation("Template")
                        .IsRequired();
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.TagTemplate", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("AnalysisTagger.Domain.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
